spring:
  application:
    name: filesharingapi

  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:postgresql://postgres:5432/filesharing_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/filesharing
          jwk-set-uri: http://keycloak:8080/realms/filesharing/protocol/openid-connect/certs

minio:
  endpoint: http://minio:9000
  public-endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin123456
  bucket: files

keycloak:
  server-url: http://keycloak:8080
  admin-realm: master
  target-realm: filesharing
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin

server:
  port: 8080