spring:
  application:
    name: filesharingapi

  datasource:
    url: jdbc:postgresql://localhost:5432/FileSharingSystemDataBase
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/filesharing


minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin123456
  bucket: files

server:
  port: 8080