services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --db=postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/FileSharingSystemDataBase
      KC_DB_USERNAME: keyloack
      KC_DB_PASSWORD: keyloack
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

volumes:
  keycloak_data:
  minio_data: